pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh '''
          # Create HelloWorld.java
          cat > HelloWorld.java <<EOF
          public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("Hello, Jenkins from Java!");
              }
          }
          EOF

          # Compile and run
          javac HelloWorld.java
          java HelloWorld
        '''
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh '''
             node --version
             
             
        '''
      }
    }
  }
}
